apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-app
  name: monitoring-app
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3000
  selector:
    app: monitoring-app
  type: NodePort
status:
  loadBalancer: {}
